---

- name: My first play
  hosts: webservers
  tasks:
   - name: install java
     ansible.builtin.yum:
     name: java
     

#   - name: Print message
#     ansible.builtin.debug:
#       msg: Hello world
